// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	BasicAuthScopes = "BasicAuth.Scopes"
)

// CreatedApplication defines model for CreatedApplication.
type CreatedApplication struct {
	Description *string `json:"description,omitempty"`
	Id          int     `json:"id"`
	Name        string  `json:"name"`

	// Secret used to trigger a deployment, store somewhere safe
	RawSecret string `json:"rawSecret"`
}

// NewApplication defines model for NewApplication.
type NewApplication struct {
	Description *string `json:"description,omitempty"`

	// A list of HTTP requests to send
	HttpTasks *[]NewHttpTask `json:"httpTasks,omitempty"`
	Name      string         `json:"name"`

	// A list oh SSH commands to run
	SshTasks *[]NewSshTask `json:"sshTasks,omitempty"`
}

// NewHttpTask defines model for NewHttpTask.
type NewHttpTask struct {
	Body *string `json:"body,omitempty"`

	// An object of Header-name:Value
	Headers *map[string]interface{} `json:"headers,omitempty"`
	Method  string                  `json:"method"`

	// The lower the number the higher the priority
	Priority int    `json:"priority"`
	Url      string `json:"url"`
}

// NewSshTask defines model for NewSshTask.
type NewSshTask struct {
	// Command to run on the target host
	Command string `json:"command"`
	Host    string `json:"host"`
	Port    int    `json:"port"`

	// The lower the number the higher the priority
	Priority int    `json:"priority"`
	Username string `json:"username"`
}

// AddApplicationJSONBody defines parameters for AddApplication.
type AddApplicationJSONBody NewApplication

// AddApplicationJSONRequestBody defines body for AddApplication for application/json ContentType.
type AddApplicationJSONRequestBody AddApplicationJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /applications)
	AddApplication(ctx echo.Context) error

	// (GET /ping)
	Ping(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// AddApplication converts echo context to params.
func (w *ServerInterfaceWrapper) AddApplication(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{"ROLE_ADMIN"})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.AddApplication(ctx)
	return err
}

// Ping converts echo context to params.
func (w *ServerInterfaceWrapper) Ping(ctx echo.Context) error {
	var err error

	ctx.Set(BasicAuthScopes, []string{"ROLE_ADMIN"})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Ping(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/applications", wrapper.AddApplication)
	router.GET(baseURL+"/ping", wrapper.Ping)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xWUXPbNgz+Kzxuj5rlpsse9LSk7S3ZrWmuzpaHXK5HS7DETiQ1AIrn5fLfd6AYW7ac",
	"9XbdzU80KAIfPgAf+ajL4LrgwTPp4lEjUBc8Qfzzqzc9NwHtX1C9QwwoxgqoRNuxDV4X+qznBjzb0ohB",
	"Wb8K6NKalLNE1tcqoLL+wbS20pluwFSAMcDt7e2nkQcQG5UNOCMr3nSgC02M1tf6SX5Z2o6n3yAYhuqs",
	"69oUX6wdhg6Q7ZDCHtqJy0zbamS2nqEGFLs3Do4eQLNeQInAUy4Gu+oJKsVBMdq6BlRGVdC1YePAc6aI",
	"A4Ki4GDdgKzMCnQ2yTXTCH/0FqHSxZ2OvEVIYwCZZkO/k77fHg/Lz1CywLyC9Vfx0jB3N9H7tOSqtcQq",
	"rNTFzc21EpxATJIygReklsHFg98irHShv8l3TZanAuZXsL5IQSRgQmAQzeYfC0DUfAFYoxaLC1UG54yv",
	"Ii7s/b+AtRgiTFEdVCVCfIH8bWoT5peh2hynfDcXB3l5NfiOnMevvpPYxW+m7UfNswPggJtQHY3SoQ1o",
	"eTMNc9OAasMaUHEDyvdumZaNrZu03J7OtLPeut7pYp4dmZ8e22MjvE/g2NuAeDj4AqfPdZlQmko9TenN",
	"sJFaQAUfk2CDNbBqAvF08jId7UepC5imfmX6lnVxcpJpZ/4caPjh9PT16YiWV8do+b/YJ8AXBujlEmwP",
	"JQpSwtmW3mlZZByh7MXBQuZnKMe5IVuKrG/lXM4sxbrjWwRGR0WXO2OoomdTRobBGdvqQjtoKjtbht5v",
	"zI+1GGdlcM9aWOj3sq/O437qncEzFXleW276pRzIo59lyIWbfdp/CuptVGe5roziEFrFjeEoJeBJemZf",
	"5mI/JWmP+ivdNSi8MjvJJZ3p1pbgKVbhGfDlzQRn6MBT6LGEWcA6T4col29Fgiy3MEaqM/0ASAP+V7P5",
	"bC6fiRfTWV3o17P57ESqZ7iJ9cj3YMn0pA4/GJZ4nSqjPKzV+PKIzjGuLyvRo6ra307cnCdlk0KCjxFG",
	"kfPPNNw1uwv+Czo8DvK037iMPUTD6LVyMp//Z9GPPC0iggNh3m2rcjihqC9LIFr1bTvcGGxqkkk7Gxfh",
	"XnbyTiayeNT1sdfER+AevTQlWde1oH5efLhSzxnHBwYQK7uK0kCAD4DSxNh7L34Pq3Y9GL+Ksn3ZdUBk",
	"atiTRN2FGGaqOofSMWHzOvh6m5+09PfzVy/VaZtFPn2jPj8UkzDp4m5Pku70xw+/vPt09vb95ZW+f7qX",
	"L4U7ih8Oo5nLJD3dP/0dAAD//70DXTEeCwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
